-- Item a: Consultando categoria por produto
SELECT
    CD_CATEGORIA,
    C.DS_CATEGORIA,
    P.CD_PRODUTO,
    P.DS_COMPLETA_PROD,
    P.VL_UNITARIO,
    P.TP_EMBALAGEM,
    P.VL_PERC_LUCRO
FROM MC_CATEGORIA_PROD C
    LEFT OUTER JOIN MC_PRODUTO P
    USING ( CD_CATEGORIA )
ORDER BY C.DS_CATEGORIA, P.DS_PRODUTO;

-- Item b: Consultando dados completos do cliente
SELECT
    NR_CLIENTE,
    C.NM_CLIENTE AS NOME,
    C.DS_EMAIL AS EMAIL,
    C.NR_TELEFONE AS TELEFONE,
    C.NM_LOGIN AS LOGIN,
    TO_CHAR(PF.DT_NASCIMENTO, 'DD-MM-YYYY') AS DATA_NASCIMENTO,
    TO_CHAR(PF.DT_NASCIMENTO, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS DIA_DA_SEMANA,
    TRUNC(MONTHS_BETWEEN(SYSDATE, PF.DT_NASCIMENTO) / 12) AS IDADE_ANOS,
    PF.FL_SEXO_BIOLOGICO AS SEXO_BIOLOGICO
FROM MC_CLI_FISICA PF
INNER JOIN MC_CLIENTE C
    USING (NR_CLIENTE);

-- Item c: Consultando dados de vizualização
SELECT
    CD_PRODUTO,
    P.DS_PRODUTO AS NOME_PRODUTO,
    V.DT_VISUALIZACAO AS DATA_VISUALIZACAO,
    V.NR_HORA_VISUALIZACAO AS HORA_VISUALIZACAO
FROM MC_SGV_VISUALIZACAO_VIDEO V
INNER JOIN MC_PRODUTO P
    USING (CD_PRODUTO)
ORDER BY V.DT_VISUALIZACAO, V.NR_HORA_VISUALIZACAO;